#Homologous strategy
server:
  servlet:
    session:
      cookie:
        http-only: false
        same-site: none
        secure: true

db:
  mysql:
    host: 127.0.0.1

  redis:
    host: 127.0.0.1
